# fly.toml app configuration file generated for hampbot on 2023-08-19T17:40:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hampbot"
primary_region = "bos"

[build]
  build-target = "runner"

[http_service]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
